### ISSUE TITLE
Cannot compile lammps tests due to missing Makefiles

### ISSUE THREAD

**Issue by HomeworkThomas** [olcf/olcf-test-harness-examples#1]
Two Makefiles that are required for the compilation of the lammps tests are not cloned into `Source/lammps/src/MAKE/` when the tests are run in the harness.  The necessary files are: `Makefile.gfx90a` and `Makefile.cray_cc`

**Comment by ddietz89** [comment]
Thanks for the report!

These got lost when dropping the source from the repo in favor of pulling from lammps' github repo. I copied them over and modified the build script to copy them in place which should fix it.

**Comment by ddietz89** [comment]
These seem to compile now on Frontier. Thanks again!
